### PR TITLE
Time method calls within a class when class is annotated with @Timed

### LINKED ISSUE #493: Be able to target classes and not only methods with TimedAspect
See discussion in https://micrometer-metrics.slack.com/archives/C662HUJC9/p1521063013000264
Suggest to make the aspect target also types (in addition to methods), so that by annotating a class, you target all public methods in that class too (due to the way spring works it does not target private/default/protected scopes).

### PR DESCRIPTION
**Pull request by sabouri**
Assuming that when a class is annotated @Timed, the expected behavior is to measure all methods of the class, this PR adds an advice to perform just that.

Resolves #493

### CODE REVIEW

**Comment by themistoklik** [comment]
any news/updates if this is going to be merged?

**Comment by makowskimateusz** [comment]
@shakuzen @izeye What do you think about it? Are you planning to pull-in this? Would be super useful for me and not only for me probably :)

**Comment by MaxZhuravsky** [comment]
any update on this one?

**Comment by makobernal** [comment]
Hello all. Is there any chance this PR can make it into the branch? I find it extremely useful, and it's much less confusing to make `@Timed` apply to classes as well, instead of methods only.

**Review by shakuzen — APPROVED** [review]
Looks good to me. Thanks @sabouri. Would you be willing to sign the CLA so we can accept your contribution?

**Pull request merged**
