### PR TITLE
export percentile values to new relic

### PR DESCRIPTION
**Pull request by jfarr**

### CODE REVIEW

**Comment by jfarr** [comment]
You also have to tell the underlying meter to publish percentiles like so:

```
Timer.builder("event.response.time")
        .publishPercentiles(.95, .99)
        .register(meterRegistry);
```
Then this will export them to New Relic.

**Comment by jkschneider** [comment]
Percentiles are already exported to new relic. For the timer `event.response.time`, if a 95th percentile is enabled there will be a metric with name `event.response.time.percentile` and tag `phi=0.95`.

**Comment by izeye** [comment]
@jkschneider Based on your comment and "invalid" label, this meant to be closed?

**Comment by jkschneider** [comment]
I think it's destined for closure, but thought I'd wait a little bit for a response in case there's something we are missing.

**Comment by jfarr** [comment]
I must've missed that, thanks.

**Comment by izeye** [comment]
@jfarr Thanks for the confirmation! Closing.

**Pull request closed without merging**
