### PR TITLE
[Stackdriver] Allow to set custom MonitoredResouce

### LINKED ISSUE #1489: [Stackdriver] Allow to set custom MonitoredResource
Currently, StackdriverMeterRegistry has hardcoded MonitoredResource with type "global" and label "project_id".

There is no possibility to set different resource type other than "global" and put more labels.
Please enhance the code to allow customization of MonitoredResource

### PR DESCRIPTION
**Pull request by YashchenkoN**
Fixes #1489

### CODE REVIEW

**Comment by YashchenkoN** [comment]
#1489

**Comment by IRus** [comment]
I feel like you shouldn't expose:
1. Monitored resource to user, instead define method that allow to customize resource as simple string
2. RESOURCE_TYPE to public

Are you sure, that labels part, can't be solved through common tags?

**Comment by YashchenkoN** [comment]
@IRus
1. Agree, fixed in a subsequent commit
2. Fixed

Yes, I checked and it seems that labels might be solved via common tags

**Comment by YashchenkoN** [comment]
Hi @shakuzen,
Could you please take a look and merge if it LGTY? Thanks

**Comment by YashchenkoN** [comment]
@shakuzen I've changed the base branch. Could you please merge this PR? It would be nice to see this change in the next version of the library.

**Comment by shakuzen** [comment]
> It would be nice to see this change in the next version of the library.

The plan is to include this in the 1.3 release. I'm just focusing on getting out patch releases for 1.1.x and 1.2.x before that. I will circle back to this soon.

**Pull request merged**
