### PR TITLE
Remove deprecated MissingRequiredConfigurationException and its usages

### PR DESCRIPTION
**Pull request by izeye**
This PR changes to use FQN to suppress the following deprecation warnings:

```
> Task :micrometer-registry-cloudwatch:compileJava
[ant:checkstyle] /Users/user/IdeaProjects/micrometer/implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchMeterRegistry.java:27: warning: [deprecation] MissingRequiredConfigurationException in io.micrometer.api.instrument.config has been deprecated
[ant:checkstyle] import io.micrometer.api.instrument.config.MissingRequiredConfigurationException;
[ant:checkstyle]                                           ^
[ant:checkstyle] /Users/user/IdeaProjects/micrometer/implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchConfig.java:19: warning: [deprecation] MissingRequiredConfigurationException in io.micrometer.api.instrument.config has been deprecated
[ant:checkstyle] import io.micrometer.api.instrument.config.MissingRequiredConfigurationException;
[ant:checkstyle]                                           ^
[ant:checkstyle] 2 warnings
```

### CODE REVIEW

**Review by jonatan-ivanov — COMMENTED** [review]
Since this was deprecated in 1.5.0, shouldn't we remove it in 2.0.0?

**Comment by izeye** [comment]
@jonatan-ivanov Yeah, it seems to be a good opportunity to clean up all those deprecations.

**Comment by jonatan-ivanov** [comment]
@izeye Do you want to remove it in 2.0 and use FQN in previous versions?

**Comment by izeye** [comment]
@jonatan-ivanov Actually, the previous version branches are using FQN already. See [this](https://github.com/micrometer-metrics/micrometer/blob/main/implementations/micrometer-registry-cloudwatch/src/main/java/io/micrometer/cloudwatch/CloudWatchConfig.java#L41), for example. It seems to have been changed in [this](https://github.com/micrometer-metrics/micrometer/commit/bb76ef62974e88802019f43a1e619c21fa2f5a65#diff-a94a6d1a7134525651dad4d38ee522198da0200058364a512b725fedcaf7e249L41) somehow.

I updated this PR to remove the `MissingRequiredConfigurationException` and its usages by aligning them with the code in the `micrometer-registry-cloudwatch2` module.

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by jonatan-ivanov** [comment]
Thanks! :)

**Pull request merged**
