### PR TITLE
Add counters for QueryPlanCacheHit and QueryPlanCacheMiss in HibernateMetrics

### PR DESCRIPTION
**Pull request by danila-m**
This PR exposes in Micrometer two new Hibernate Metrics : QueryPlanCacheHit and QueryPlanCacheMiss.

### CODE REVIEW

**Comment by educhastenier** [comment]
:question: Why this contribution in HibernateMetrics and not in **HibernateQueryMetrics**?

**Comment by shakuzen** [comment]
> Why this contribution in HibernateMetrics and not in **HibernateQueryMetrics**?

It is not per-query metrics - it is metrics across all queries, so there is not a cardinality concern with many different queries.

**Review by shakuzen — APPROVED** [review]

**Review by shakuzen — APPROVED** [review]
Thank you for the contribution. Looks good to me.

**Comment by educhastenier** [comment]
> > Why this contribution in HibernateMetrics and not in **HibernateQueryMetrics**?
> 
> It is not per-query metrics - it is metrics across all queries, so there is not a cardinality concern with many different queries.

Thx for this explanations, I had missed this subtility :relieved:

**Pull request merged**
