### PR TITLE
Separate ZGC-dependent test from JvmGcMetricsTest

### PR DESCRIPTION
**Pull request by izeye**
This PR separates ZGC-dependent test from `JvmGcMetricsTest`.

### CODE REVIEW

**Review by shakuzen — COMMENTED** [review]
There's nothing specific to ZGC in that test case. It's demonstrating the issue described in https://github.com/micrometer-metrics/micrometer/issues/2561, which I could have made more clear in a comment or something.

**Comment by izeye** [comment]
@shakuzen "Pauses" and "Cycles" in `GarbageCollectorMXBean.getName()` seem to be specific to ZGC as G1 GC doesn't seem to have them, for example. Am I missing something?

**Comment by shakuzen** [comment]
I should have looked at the test more closely before commenting. Still, Shenandoah and ZGC use similar names for the GCMXBean names, so as mentioned [here](https://github.com/micrometer-metrics/micrometer/pull/2795/files#r716861120) the test demonstrates the issue for those two collectors. The underlying issue of collections happening before binding not being counted is not limited to those two collectors, though, so the test could probably be written better. I suspect I didn't polish it because it is disabled until we can get a fix for #2561

**Comment by izeye** [comment]
@shakuzen Thanks for the quick feedback! Sounds better to be resolved in #2561, then. Closing.

**Pull request closed without merging**
