### PR TITLE
Implement a CloudWatch EmbeddedMetricFormat (EMF) registry

### PR DESCRIPTION
**Pull request by ksletmoe-aws**
I based this heavily off of the existing CloudWatch2 registry and tried to maintain attribution comments where it made sense.

### CODE REVIEW

**Comment by ksletmoe-aws** [comment]
There should already be a corporate CLA signed by my employer (Amazon).

**Comment by jonatan-ivanov** [comment]
Thank you for the PR!

CLA:
Could you please check what happens if you click on the first link in the comment of the cla-bot? Do you get an error or does the page says that the CLA is signed?
If the latter, could you please click on sync (second link in the comment).

EMF:
Micrometer supports CloudWatch, you don't need to log your metrics out in EMF if you just want to use CloudWatch. Would the CloudWatchMeterRegistry work for you?

**Comment by ksletmoe-aws** [comment]
CLA:
I clicked the sync -- it seems it's not finding our agreement. Is it possible for you to check if it's been signed for @amazon.com domains? Our legal team seems to think that it is.

EMF:
In addition to the concerns Qi Chen raised in [#3112](https://github.com/micrometer-metrics/micrometer/issues/3112), EMF is useful if you are already publishing logs and/or metrics with a CloudWatch Agent or Firelens sidecar in ECS, as there's less configuration changes needed. You also don't need to inject a null object CloudWatch client or modify your code to skip setting up a metric registry in a dev environment with EMF -- you can simply just not run an EMF publisher and metrics will not be sent anywhere. Lastly, EMF gives more flexibility for how to handle failed batches because you are offloading the actual publishing to another process, which can be configured to retry batches, keep metrics on disk, etc in the event CloudWatch is unreachable.

**Comment by ksletmoe-aws** [comment]
I spoke with @jonatan-ivanov on Slack, and they were able to help me determine that the CLA has been signed by somebody in the amzn github organization. I joined that organization. Trying to sync the PR via the above link but still no dice on the CLA approval workflow. Suspect there might be some propagation delay

**Comment by ksletmoe-aws** [comment]
Wanted to check in and see if this review has any feedback or will be accepted

**Comment by ksletmoe-aws** [comment]
It was decided that this should be hosted in a different repository.

**Comment by jonatan-ivanov** [comment]
Could you please add a link to that repo here so that the next person who might need it will find it?

**Comment by jonathannaguin** [comment]
Does this repository exist? @ksletmoe-aws

**Pull request closed without merging**
