### PR TITLE
Add Elastic support

### PR DESCRIPTION
**Pull request by tkp1n**
Proposal for issue #154 

Basically a re-implementation of the [elasticsearch-metrics-reporter-java](https://github.com/elastic/elasticsearch-metrics-reporter-java) for micrometer.

@jkschneider

### CODE REVIEW

**Comment by tkp1n** [comment]
So I just took the elastic implementation for a spin.

Running a local instance of both elasticsearch and kibana is as simple as:
`docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk:600`

Running the `CounterSample` from the repository pushed the following information into ES and kibana:
countersample_data

A visualization of the rate at which the counters arrive:
countersample_rateviz

And a visualization of the acutal value (the max value per 30 seconds interval/bucket):
countersample_valueviz


Running the `TimerSample` from the repository pushed the following information into ES and kibana:
timersample_data

A visualization of timer values (the max timer value per 30 seconds interval/bucket):
timersample_maxmeanper30sec

I'm sure some kibana champion could produce nicer charts, sorry about that.
(Both samples were run with the default configuration)

**Comment by jkschneider** [comment]
Working on merging this now. Some changes coming:

1. We will make `_type` = 'metric' for all meter types going forward, as in ES 6, indexes may now no longer have more than one distinct `_type`. See [this](https://www.elastic.co/guide/en/elasticsearch/reference/6.0/removal-of-types.html#_why_are_mapping_types_being_removed).

**Comment by jkschneider** [comment]
> Why not "_type": "doc"?

Changed to "doc" as you suggested. Unless you see it as really important, I think we'll stay away from making it configurable for now, as the whole concept of type is going away in future ES releases.

**Comment by jkschneider** [comment]
Merged in 3ec44d958736b0e4c6979479cbc2982fd491384b. I expect we'll make further tweaks, but we have at least some implementation on master now!

**Comment by tkp1n** [comment]
Did you really intent to add a System.out.println(); here?

https://github.com/micrometer-metrics/micrometer/blob/3ec44d958736b0e4c6979479cbc2982fd491384b/micrometer-core/src/main/java/io/micrometer/core/instrument/step/StepFunctionTimer.java#L79

Thanks for your work on the PR!

**Comment by jkschneider** [comment]
Oops. Thanks!

**Comment by quzhixue-Kimi** [comment]
Hi dear, 
Do you mean that if I would like to use the es as the metrics storage, the version of spring boot must be 2.1.0 or greater?
Currently, spring boot 2.0.5 is used but, failed.

BR
Kimi

**Comment by izeye** [comment]
@quzhixue-Kimi Yes, as you can see, the Elasticsearch meter registry support has been added since 1.1.0 (1.1.0-rc.1) and Spring Boot 2.1.0 is compatible with Micrometer 1.1.0, so you should use Spring Boot 2.1.0 or later.

**Comment by quzhixue-Kimi** [comment]
@izeye, thank you for your feedback.

**Comment by cykl** [comment]
Hey @quzhixue-Kimi. If 2.1 is not yet an option for you, I successfully backported ES autoconfiguration (and micrometer 1.1.0) to Boot 2.0. IIRC it took me less than an hour and was quite easy.

**Comment by quzhixue-Kimi** [comment]
@cykl , it is appreciated that you may share your git repository as you mention.

BR
Kimi

**Pull request closed without merging**
