### PR TITLE
New Relic Micrometer Spring Legacy Updates

### PR DESCRIPTION
**Pull request by neiljpowell**
Updates for New Relic properties added in Micrometer v1.3.0 related to
<https://github.com/spring-projects/spring-boot/pull/18472> per @shakuzen comment

### CODE REVIEW

**Comment by shakuzen** [comment]
Thanks for porting the changes back over here.
Could you rebase and target this at the `1.3.x` branch? We'll actually be deleting the micrometer-spring-legacy module from `master` soon.

**Comment by neiljpowell** [comment]
@shakuzen Rebase showed no changes so I edited the target/base branch of the PR.  Let me know if I need to do anything else.

**Comment by shakuzen** [comment]
> Rebase showed no changes so I edited the target/base branch of the PR. Let me know if I need to do anything else.

After changing the target, there are commits and changed files added to the pull request. Just to share, the steps I take to rebase for the new target branch in this case are:

```sh
# on the branch for this pull request
# it was targeting master so make sure it has the latest of those
git rebase master
# move only pull request commits to 1.3.x
git rebase --onto 1.3.x master newrelic-spring-legacy
# resolve conflicts, if any
```
I'll go ahead and do that so this PR is unblocked.

**Comment by neiljpowell** [comment]
@shakuzen Thank you for sharing. I have not had to do that before.

**Pull request merged**
