### PR TITLE
Apply NoHttpCheck

### PR DESCRIPTION
**Pull request by izeye**
This PR applies `NoHttpCheck` Checkstyle moodule.

This PR also updates HTTP URLs to HTTPS URLs.

See https://github.com/spring-io/nohttp

### CODE REVIEW

**Comment by shakuzen** [comment]
Does this work with older versions of Gradle? If so, it seems better to make this change in all the maintenance branches also.

**Comment by izeye** [comment]
@shakuzen Thanks for the feedback!

I confirmed that it works on the 1.1.x branch, so I changed the base branch to the 1.1.x branch. I also updated dependency locks for the `checkstyleNoHttp` task as follows:

```
./gradlew checkstyleNoHttp --update-locks io.spring.nohttp:nohttp-checkstyle
```

**Comment by izeye** [comment]
For the record, there were some dependency lock files that I missed accidentally when I was creating this PR as follows:

```
$ git status
On branch nohttp
Your branch is up to date with 'origin/nohttp'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        benchmarks/benchmarks-core/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-azure-monitor/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-ganglia/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-graphite/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-humio/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-influx/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-jmx/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-kairos/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-new-relic/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-prometheus/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-signalfx/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-stackdriver/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-statsd/gradle/dependency-locks/checkstyle.lockfile
        implementations/micrometer-registry-wavefront/gradle/dependency-locks/checkstyle.lockfile
        micrometer-jersey2/gradle/dependency-locks/checkstyle.lockfile
        micrometer-test/gradle/dependency-locks/checkstyle.lockfile
        samples/micrometer-samples-boot1/gradle/dependency-locks/checkstyle.lockfile
        samples/micrometer-samples-core/gradle/dependency-locks/checkstyle.lockfile

nothing added to commit but untracked files present (use "git add" to track)
$
```

I won't create a PR for them as the build seemed to be successful without them. Let me know if they are necessary somehow.

**Comment by shakuzen** [comment]
For reasons I don't understand, there are lockfiles that will be generated by Gradle but not required by it when building. The checkstyle task seems to be one of those.

**Pull request merged**
