### PR TITLE
Constructors to customize InstrumentedQueuedThreadPool

### LINKED ISSUE #1639: Add ability to customize InstrumentedQueuedThreadPool
Right now [InstrumentedQueuedThreadPool](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jetty/InstrumentedQueuedThreadPool.java) can be constructed with default underlying values only by implicitly calling no-arg `QueuedThreadPool` constructor, which looks like this:
```java
public QueuedThreadPool()
{
    this(200);
}
```
While I assume default logic might be useful in some cases, having an opportunity to tweak it is something I would really like to have (I have finely tuned threadpool in production). 

If team is fine with this proposal I can provide a PR, which will add bunch of overloaded constructors.

### PR DESCRIPTION
**Pull request by IgorPerikov**
I decided to provide all possible constructors for convenience and further simplicity of using (although with one big constructor, people might figure out what to pass to the missing parameters, it's still not as good as plenty of 'native' options)

fixes #1639

### CODE REVIEW

**Comment by IgorPerikov** [comment]
@shakuzen Would you mind taking a look?

**Comment by IgorPerikov** [comment]
@shakuzen @izeye kindly ping

**Comment by shakuzen** [comment]
Sorry for the delay on review here. I plan to start reviewing things planned for 1.4 once I finish the patch releases this week.

**Comment by michaelbannister** [comment]
We have (a subset of) this same code in our app, and it'd be nice to replace it with using the class directly provided by Micrometer.

**Pull request merged**
