### PR TITLE
Micrometer registry appdynamics

### PR DESCRIPTION
**Pull request by rjmveloso**
This PR contributes with a registry for AppDynamics #575

### CODE REVIEW

**Comment by rjmveloso** [comment]
CircleCi is failing because there is no baseline for AppDynamics yet.

**Comment by jonatan-ivanov** [comment]
@rjmveloso You can disable that check: [see here](https://github.com/micrometer-metrics/micrometer/blob/e904ffd9bca5c8079bde69eb89b27f171784ed88/build.gradle#L327)

**Comment by rjmveloso** [comment]
Thank you @jonatan-ivanov, I ran it locally with `-PcompatibleVersion=SKIP`.
I believe this would be removed from the condition after a first release of the module.

**Comment by rjmveloso** [comment]
> @rjmveloso You can disable that check: [see here](https://github.com/micrometer-metrics/micrometer/blob/e904ffd9bca5c8079bde69eb89b27f171784ed88/build.gradle#L327)

Think your suggestion and my previous observation relates with the issue https://github.com/micrometer-metrics/micrometer/issues/3486

**Comment by rjmveloso** [comment]
It seems Gradle Plugin Portal was facing some outages leading to the following problem (version not in maven central):
```
Could not find org.ajoberstar.grgit:grgit-core:4.0.2.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/ajoberstar/grgit/grgit-core/4.0.2/grgit-core-4.0.2.pom
       - https://plugins.gradle.org/m2/org/ajoberstar/grgit/grgit-core/4.0.2/grgit-core-4.0.2.pom
 ```
 
 It is possible to force a rerun of the actions and also if possible to have a core review?

**Review by shakuzen — COMMENTED** [review]
As far as I can tell, all tag info is dropped from publishing. Is that correct? That's a lot of valuable information lost. I'm not sure we would want to support that in the Micrometer repo. Does AppDynamics not support dimensions (tags) on metrics?

**Comment by rjmveloso** [comment]
> As far as I can tell, all tag info is dropped from publishing. Is that correct? That's a lot of valuable information lost. I'm not sure we would want to support that in the Micrometer repo. Does AppDynamics not support dimensions (tags) on metrics?

You are correct. There is no direct way to publish tags with AppDynamics agent.
Maybe a solutions would be to create sub-paths for any Custom Metric for each tag, but in the end it will be just replicated metrics with the same values. I will investigate it further.

**Comment by rjmveloso** [comment]
> As far as I can tell, all tag info is dropped from publishing. Is that correct? That's a lot of valuable information lost. I'm not sure we would want to support that in the Micrometer repo. Does AppDynamics not support dimensions (tags) on metrics?

@shakuzen There is no support for tags/dimensions on AppDynamics.
I cannot provide further support because I don't have access to appd anymore.
If AppDynamics have support for OpenTelemetry (as read in some thread related with the subject) I would suggest anyone interested to go for it and use otlp micrometer exporter .

**Pull request closed without merging**
