### PR TITLE
Upgrade to Gradle Wrapper 4.8.1

### PR DESCRIPTION
**Pull request by izeye**
This PR upgrades to Gradle Wrapper 4.8.1.

### CODE REVIEW

**Comment by shakuzen** [comment]
@jkschneider should this PR be targeted at the `1.0.x` branch and then we can merge forward to `master` post merge?

**Comment by izeye** [comment]
@shakuzen @jkschneider Is it preferable to target to the 1.0.x branch for everything except missing or breaking changes?

**Comment by jkschneider** [comment]
@izeye Trying to keep feature enhancements out of 1.0.x as well, unless it's a situation of "broken by omission". 1.1.0 will be coming up pretty shortly anyway.

**Comment by jkschneider** [comment]
Merged with 2fcff674.

**Comment by izeye** [comment]
@jkschneider Thanks for clarification :+1:

**Pull request closed without merging**
