### PR TITLE
Upgrade to JMH Gradle plugin 0.6.2

### PR DESCRIPTION
**Pull request by izeye**
This PR upgrades to JMH Gradle plugin 0.6.2.

### CODE REVIEW

**Review by shakuzen — APPROVED** [review]
Thanks, as always. Can we easily apply this to the 1.3.x branch? If so, I'd like to keep this configuration up-to-date and consistent across maintenance branches.

**Comment by izeye** [comment]
@shakuzen JMH Gradle plugin 0.6.2 seems to [require Gradle 6.8 or later](https://github.com/melix/jmh-gradle-plugin#what-plugin-version-to-use), so it doesn't seem to be able to apply it to the 1.3.x branch. Is it okay with applying it to the 1.5.x branch and later?

**Comment by shakuzen** [comment]
> Is it okay with applying it to the 1.5.x branch and later?

Yes, that's fine. I've updated the milestone.

**Comment by izeye** [comment]
@shakuzen Thanks for the quick feedback! I changed the base branch to the 1.5.x.

For the record, I updated dependency locks as follows:

```
./gradlew clean check downloadDependencies --update-locks org.openjdk.jmh:jmh-core,org.openjdk.jmh:jmh-generator-annprocess
```

**Pull request merged**
