### PR TITLE
Improve Tag propagation: annotation on parameters

### PR DESCRIPTION
**Pull request by jonatan-ivanov**
See the second item of #1586

### CODE REVIEW

**Comment by izeye** [comment]
This might have been closed unintentionally due to the default branch rename as it has been closed without explanation.

**Comment by jonatan-ivanov** [comment]
@izeye Thanks for letting us know, GH closed these because the original branch does not exist anymore.

**Comment by izeye** [comment]
I wonder why those have been closed as [GitHub seems to claim that renaming a branch will "Re-target any open pull requests"](https://github.com/github/renaming#renaming-existing-branches). There are other pull requests that have been created against the `master` branch but re-targeted to the `main` branch successfully like https://github.com/micrometer-metrics/micrometer/pull/568.

**Comment by shakuzen** [comment]
@izeye I guess GitHub needs the source fork to exist for it to re-target. If that still exists, it has been retargeted. If it does not exist anymore, the pull request got automatically closed. We can't even reopen because of the fork not existing.

**Comment by jonatan-ivanov** [comment]
fyi: I pushed this back but GH does not care (I guess since it is a different fork): https://github.com/micrometer-metrics/micrometer/compare/micrometer-metrics:micrometer:main...jonatan-ivanov:micrometer:metric-tag

**Pull request closed without merging**
