### PR TITLE
Fix brittle assertion for tomcat.global.sent

### PR DESCRIPTION
**Pull request by izeye**
The current assertion for the `tomcat.global.sent` metric depends on 405 HTML response body from Tomcat, and it has been changed from Tomcat 8.5.47 to 8.5.49.

From Tomcat 8.5.47:

```
<!doctype html><html lang="en"><head><title>HTTP Status 405 – Method Not Allowed</title><style type="text/css">h1 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:22px;} h2 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:16px;} h3 {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;font-size:14px;} body {font-family:Tahoma,Arial,sans-serif;color:black;background-color:white;} b {font-family:Tahoma,Arial,sans-serif;color:white;background-color:#525D76;} p {font-family:Tahoma,Arial,sans-serif;background:white;color:black;font-size:12px;} a {color:black;} a.name {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 405 – Method Not Allowed</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> HTTP method GET is not supported by this URL</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource.</p><hr class="line" /><h3>Apache Tomcat/8.5.47</h3></body></html>
```

From Tomcat 8.5.49:

```
<!doctype html><html lang="en"><head><title>HTTP Status 405 – Method Not Allowed</title><style type="text/css">body {font-family:Tahoma,Arial,sans-serif;} h1, h2, h3, b {color:white;background-color:#525D76;} h1 {font-size:22px;} h2 {font-size:16px;} h3 {font-size:14px;} p {font-size:12px;} a {color:black;} .line {height:1px;background-color:#525D76;border:none;}</style></head><body><h1>HTTP Status 405 – Method Not Allowed</h1><hr class="line" /><p><b>Type</b> Status Report</p><p><b>Message</b> HTTP method GET is not supported by this URL</p><p><b>Description</b> The method received in the request-line is known by the origin server but not supported by the target resource.</p><hr class="line" /><h3>Apache Tomcat/8.5.49</h3></body></html>
```

This PR changes it to depend on values from "Content-Length" headers.

### CODE REVIEW

**Comment by checketts** [comment]
Sorry I didn't comment on this PR earlier. I think we might want a better fix like provided in https://github.com/micrometer-metrics/micrometer/pull/1715#issuecomment-557178927 by @tomakehurst .  That way we just use our own response instead of relying on the Tomcat 405 for the content

**Comment by izeye** [comment]
@checketts @tomakehurst Sorry, I missed the conversation. When I was creating this, I thought it's testing an error intentionally, which gives better coverage.

**Comment by shakuzen** [comment]
> When I was creating this, I thought it's testing an error intentionally, which gives better coverage.

That's a good point. I think it's a good idea to check that the metrics change as expected for both successful and failed requests. The changes in https://github.com/micrometer-metrics/micrometer/pull/1715#issuecomment-557178927 don't include any errors. Maybe a more straightforward way would be to implement an error handler that returns a known response, but the changes in this pull request seem to have fixed the brittleness by comparing the bytes received by the http client to the server metrics. I'm leaning towards keeping the changes made in this PR unless someone still thinks another approach would be better. Let me know if I'm missing something.

**Comment by checketts** [comment]
I'm fine with @izeye 's fix (And Thankful for hi excellent efforts!) I like that the test now uses the content length to drive the assertion. I merely was interested to see the same build failure solved 2 different ways and wanted to point that out.

Thanks for all you folks do!

**Pull request merged**
