### PR TITLE
Apply NamingConvention to tags for OtlpMeterRegistry

### PR DESCRIPTION
**Pull request by izeye**
This PR applies `NamingConvention` to tags for `OtlpMeterRegistry`.

See https://github.com/micrometer-metrics/micrometer/issues/4053#issuecomment-1702959975

### CODE REVIEW

**Review by shakuzen — COMMENTED** [review]
Thanks for the pull request. I think this is more a bug than a new feature, so it should go to the latest affected maintenance branch. Would you rebase it on that and update the target branch?

**Comment by izeye** [comment]
@shakuzen Sure, should this be targeted on 1.12.x (OSS support) or 1.9.x (commercial support)?

**Comment by jonatan-ivanov** [comment]
I feel we should fix this in `1.9.x` and merge it forward. @shakuzen?

**Comment by izeye** [comment]
@jonatan-ivanov Thanks for the feedback!

I switched the base branch to 1.9.x.

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by jonatan-ivanov** [comment]
Thank you!

**Pull request merged**
