### PR TITLE
add min statistic for distribution summaries and timers (#457)

### PR DESCRIPTION
**Pull request by thrxde**
to use StatisticSet for CloudwatchMetrics, minimum and maximum statistic value is required

### CODE REVIEW

**Comment by massamany** [comment]
The TimeWindowMin would be obsolete with the proposition in #2033. But I did not go as far with the integration in the summaries. Merging the 2 PR could give something good, by adding not only min, but other stats (freq for instance seems very interesting to me) :-)

**Comment by thrxde** [comment]
> The TimeWindowMin would be obsolete with the proposition in #2033. But I did not go as far with the integration in the summaries. Merging the 2 PR could give something good, by adding not only min, but other stats (freq for instance seems very interesting to me) :-)

#2033 Interesting approach. But didn't try to implement a concret "CloudwatchDistributionSummary". I tryed to extend the interface to provide the min value to all the regestry implementations. 
I don't know if this is nesessary for the other fields like "freq" and "age".  I think we need some help from micrometer experts.

**Comment by jkschneider** [comment]
@thrxde I think I'd state a preference for limiting min to just the Cloudwatch implementation, because there is some history behind instrumentation containing min and it never really being used anywhere in testing for availability, so it's just extra overhead with no benefit?

But there is clearly a benefit to meeting the expectations of Cloudwatch.

**Comment by thrxde** [comment]
@jkschneider thanks for the response. So I will close this PR and try to limit the "min" feature to Cloudwatch.

**Pull request closed without merging**
