### PR TITLE
Handle empty histogram distribution in Stackdriver registry

### LINKED ISSUE #1001: Stackdriver metrics not ending up in Stackdriver
Micrometer version: 1.1.0
Spring boot version: 5.1.0
JDK version: 11

There seem to be multiple issues with the Stackdriver integration of Micrometer:
1. Metrics are created, but are not under the Global resource it seems. (The ones with global were created using our current solution) See also the screenshot below.
missing-global
2. When debugging, the `StackdriverMeterRegistry#publish` call is just done once. With the `LoggingMeterRegistry`, the publish-method is called every interval.
3. Any way of using Spring integration with actuator?
4. Feature request: Can we use the prefix for the custom metric, so instead of `custom/jvm/buffer/etc` something like `custom/{prefix}/jvm/buffer/etc`? This makes it much easier to distinguish between services running in the same project.
5. I'm also missing the documentation right now. ;-)

See also the demo zip I have added for my sample code.
[monitoringdemo.zip](https://github.com/micrometer-metrics/micrometer/files/2576517/monitoringdemo.zip)

### PR DESCRIPTION
**Pull request by itzg**
The meter `jvm.gc.pause` was causing an `ArrayIndexOutOfBoundsException` when initially exporting since the `StepTimer` did not contain any histogram buckets.

The id of the meter that failed in my case was 

```
MeterId{name='jvm.gc.pause', tags=[tag(action=end of minor GC),tag(cause=Allocation Failure)]}
```

and contained a snapshot of
```
HistogramSnapshot{count=0, total=0.0, mean=0.0, max=2.0E7}
```

There are not any existing unit tests that I could update to verify my change, so I instead verified it by hand with a Spring Boot application. I verified the GCP Stackdriver metrics request included all expected entries especially the `jvm/gc/pause`:
```
time_series {
  metric {
    labels {
      key: "cause"
      value: "Allocation Failure"
    }
    labels {
      key: "action"
      value: "end of minor GC"
    }
    type: "custom.googleapis.com/jvm/gc/pause/max"
  }
  resource {
    type: "global"
    labels {
      key: "project_id"
      value: "...."
    }
  }
  metric_kind: GAUGE
  value_type: DOUBLE
  points {
    interval {
      end_time {
        seconds: 1547588380
        nanos: 376000000
      }
    }
    value {
      double_value: 29.0
    }
  }
}
```

Fixes #1001

### CODE REVIEW

**Comment by itzg** [comment]
Oops, I'll re-open a new PR after rebasing my changes onto the `1.1.x` branch.

**Comment by itzg** [comment]
@shakuzen I now remember where I got stuck before with adding a unit test:

```
14:43:06.858 [main] ERROR io.micrometer.stackdriver.StackdriverMeterRegistry - unable to create stackdriver client
java.io.IOException: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
	at com.google.auth.oauth2.DefaultCredentialsProvider.getDefaultCredentials(DefaultCredentialsProvider.java:132)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:127)
	at com.google.auth.oauth2.GoogleCredentials.getApplicationDefault(GoogleCredentials.java:100)
	at com.google.api.gax.core.GoogleCredentialsProvider.getCredentials(GoogleCredentialsProvider.java:59)
	at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:132)
	at com.google.cloud.monitoring.v3.stub.GrpcMetricServiceStub.create(GrpcMetricServiceStub.java:173)
	at com.google.cloud.monitoring.v3.stub.MetricServiceStubSettings.createStub(MetricServiceStubSettings.java:187)
	at com.google.cloud.monitoring.v3.MetricServiceClient.<init>(MetricServiceClient.java:156)
	at com.google.cloud.monitoring.v3.MetricServiceClient.create(MetricServiceClient.java:137)
	at io.micrometer.stackdriver.StackdriverMeterRegistry.start(StackdriverMeterRegistry.java:114)
	at io.micrometer.stackdriver.StackdriverMeterRegistry.<init>(StackdriverMeterRegistry.java:100)
	at io.micrometer.stackdriver.StackdriverMeterRegistry.<init>(StackdriverMeterRegistry.java:84)
	at io.micrometer.stackdriver.StackdriverMeterRegistryTest.<init>(StackdriverMeterRegistryTest.java:35)
...TRIMMED...
```

where the initiating line is last one in my new code here:

```
public class StackdriverMeterRegistryTest {
    private final MockClock clock = new MockClock();

    // accepts all the defaults
    private StackdriverConfig config = (key -> null);

    private StackdriverMeterRegistry meterRegistry =
        new StackdriverMeterRegistry(config, clock);
```

**Comment by shakuzen** [comment]
@itzg I see. That is problematic for testing. It looks like some access will have to be made package private for testing purposes.

**Comment by itzg** [comment]
As for the authentication part, I can resolve that locally but not sure your CI will handle that. I’ll take a look around at some of the other SaaS registries like Datadog and see how unit testing was done there.

**Comment by shakuzen** [comment]
@itzg I've been manually testing locally and would like to get this fix included in our 1.1.3 release this week. Even if you can't get to the unit testing part of it, would you be able to open this pull request against the 1.1.x branch? Thanks!

**Comment by itzg** [comment]
Absolutely! We’ve had a couple other teams here run into this issue.

**Pull request closed without merging**
