### PR TITLE
Remove native-image.properties from micrometer-core

### PR DESCRIPTION
**Pull request by zakkak**
Closes https://github.com/micrometer-metrics/micrometer/issues/4245

### CODE REVIEW

**Comment by zakkak** [comment]
@pivotal-cla I am a Red Hat employee and should be covered by a corporate CLA. Additionally this might be an Obvious Fix.

**Comment by shakuzen** [comment]
@zakkak For corporate CLAs to be recognized by the CLA bot, it depends on whether your company's corporate CLA was done via a GitHub org or a corporate email domain. Depending on which, you'll need to either associate a RedHat email address with this GitHub account or make your membership public to the RH org that was used to sign the corporate CLA so the bot can see it. See the corporate section of the CLA bot FAQ: https://cla.pivotal.io/about

**Comment by zakkak** [comment]
@shakuzen AFAIK there is no redhat organization on github and the CLA was probably done with the corporate email domain. I have my redhat email associated with my github profile and am also using it in my commits.

It looks like @DanHeidinga had similar issues in the past (see https://github.com/micrometer-metrics/micrometer/pull/2514). Dan do you recall how you got this working?

**Comment by DanHeidinga** [comment]
> It looks like @DanHeidinga had similar issues in the past (see #2514). Dan do you recall how you got this working?

I think I had an email exchange with "cla@pivotal.io" but I don't have access to those email anymore to confirm.

**Comment by shakuzen** [comment]
@pivotal-cla This is an Obvious Fix

**Comment by shakuzen** [comment]
I've marked this as an obvious fix - there isn't another way we could go about achieving this and it is deleting a one line (other than license) metadata file. Thank you for the contribution.

If you would like to pursue making sure the CLA bot recognizes you as covered by a corporate CLA, I would recommend reaching out to someone internally at RedHat that deals with corporate CLAs to get instructions from them on what you are supposed to do to contribute to projects under the "Spring" Pivotal CLA. I don't remember exactly what was done when this came up 3 years ago for Dan's contribution, but he does still show as fulfilling CLA requirements.

**Pull request merged**
