### PR TITLE
Dynatrace registry v1: Truncate tag value to maximum length

### LINKED ISSUE #2339: Dynatrace dimension length constraint not honored
Hi,

We are enabling Dynatrace Register for micrometer.
Below is the output we get.
It seems like the URI is too long for the dimension accepted in Dynatrace.
Any suggested workarounds for this?

`2020-11-05 14:02:09.920 lvl=ERROR : failed to send metrics to dynatrace: 
{
    "error": {
        "code": 400,
        "message": "Constraints violated.",
        "constraintViolations": [
            {
                "path": "series[68].dimensions.uri",
                "message": "Value exceeds maximum length.Maximum value length: 128 (inclusively).",
                "parameterLocation": "PAYLOAD_BODY",
                "location": null
            },
            {
                "path": "series[70].dimensions.uri",
                "message": "Value exceeds maximum length.Maximum value length: 128 (inclusively).",
                "parameterLocation": "PAYLOAD_BODY",
                "location": null
            },
            {
                "path": "series[69].dimensions.uri",
                "message": "Value exceeds maximum length.Maximum value length: 128 (inclusively).",
                "parameterLocation": "PAYLOAD_BODY",
                "location": null
            },
            {
                "path": "series[67].dimensions.uri",
                "message": "Value exceeds maximum length.Maximum value length: 128 (inclusively).",
                "parameterLocation": "PAYLOAD_BODY",
                "location": null
            }
        ]
    }
}`

### PR DESCRIPTION
**Pull request by pirgeo**
Fixes #2339.

### CODE REVIEW

**Review by shakuzen — APPROVED** [review]
Thanks

**Comment by shakuzen** [comment]
Merged as 81aca93 and polished with 59ad9fa035becc3cb282c1a1cd8e4c9f396185a7. Thanks again. This has been applied to 1.3.x and all maintained branches so it will be included in the next patch releases we do.

**Comment by shakuzen** [comment]
@jonatan-ivanov can you take care of merging it into the in-progress dynatrace branch?

**Comment by jonatan-ivanov** [comment]
@pirgeo: Thank you very much for fixing this.
@shakuzen, @pirgeo: I merged master back so it is up-to-date now: https://github.com/micrometer-metrics/micrometer/commit/2db046a60411640ff47550f49da17660bc2739cd

@all:
I wanted to check Micrometer's `StringUtils` and commons-lang's `StringUtils` too to see if is there any 'truncate'/'substring' implementation handy that can handle Unicode characters that are consist of more than one `char`. 

I don't think it is a big issue, I don't think we should change the current implementation, I just want us to keep in mind that here's what could happen with the current implementation (in case anyone will report any issues regarding this in the future):
- Java is using UTF-16 to represent Strings
- Because of this, one character can be represented by two or more `char`s:
  - The length of `a` is 1
  - The length of `𝕒` is 2
  - The length of `👩‍💻` is 5
- So if substring will cut in the middle of these, we might get an invalid character or a new character or both.
- I don't think it is a huge issue since this should be extremely rare and the user-provided value is already modified.

A few examples to demo this:
```java
System.out.println(StringUtils.truncate("a𝕓𝕔", 4));     // a𝕓? (invalid character; original length: 5)
System.out.println(StringUtils.truncate("abcd👩‍💻", 6));   // abcd👩 (new character; original length: 9)
System.out.println(StringUtils.truncate("ab👩‍💻", 6));    // ab👩‍? (both; original length: 7)
```

Shameless plug: if you want to learn more: https://develotters.com/posts/confusing-java-strings/

**Pull request closed without merging**
