### PR TITLE
Add micrometer-registry-dolphindb

### PR DESCRIPTION
**Pull request by liuwb2001**
DolphinDB is a high-performance distributed time-series database that integrates a powerful programming language and a high-capacity and high-speed streaming data analysis system, providing a one-stop solution for rapid storage, retrieval, analysis and calculation of massive structured data, suitable for quantitative finance and industrial IoT, etc. I use DolphinDB as an implementation and it has passed the `dockerTest`.

### CODE REVIEW

**Comment by liuwb2001** [comment]
Sure. I have removed the 'build' folder.

**Comment by liuwb2001** [comment]
I have passed the 6 checks. Could you spend some time reviewing it and merge the branch to the `main` branch?

**Comment by shakuzen** [comment]
Thank you for the pull request @liuwb2001. This is the first time I'm seeing a request for supporting a registry for DolphinDB in Micrometer. I don't think anyone on the Micrometer team has experience with DolphinDB, so it may be a challenge for us to maintain this integration. We want to make sure that anything we release from the Micrometer org is something that we can maintain long-term and offer the best integration possible. I worry that we may not be able to do this with a DolphinDB registry due to our lack of expertise and familiarity with DolphinDB. I see that you already have this repository: https://github.com/liuwb2001/micrometer-registry-dolphindb. Is this published anywhere so that users can consume it without building the repository themselves? I think it may be a better option for now to maintain the Micrometer registry for DolphinDB in your repository. It will be easier for you to support users of it and make necessary changes outside of the release cycle of the Micrometer repository that way. If you want to pursue that route, please use a different group ID (not `io.micrometer`) for the published artifact so it is clear it is outside of the Micrometer org. We could help with any Micrometer questions that come up in maintaining the external repository. And we could add a link to the repository from the Micrometer website as a third-party integration once things are setup. What do you think?

**Comment by peeyee** [comment]
We have noticed that Micrometer provides convenient and effective monitoring for Java applications with its well-designed abstractions, which has resulted in a rapid increase in popularity within Git projects. Therefore, we are interested in integrating with Micrometer to offer Java users a comprehensive and streamlined monitoring solution. This integration would also contribute to enhancing the impact of both our products.

We understand the concerns you raised in pr#3856, and they are indeed valid. To address them, we are happy to offer complimentary training and technical support to assist you in gaining a deeper understanding of DolphinDB.

Allow me to provide a brief introduction to DolphinDB: it is a distributed time-series database known for its powerful data analysis capabilities. It seamlessly combines batch and streaming processing. Currently, DolphinDB ranks 6th in the DBENGINES Time Series ranking. You can find the official documentation at the following address：

https://github.com/dolphindb/Tutorials_EN

Please feel free to reach out if you have any further questions or require additional information.

**Comment by peeyee** [comment]
Hello,

We have noticed that Micrometer provides convenient and effective monitoring for Java applications with its well-designed abstractions, which has resulted in a rapid increase in popularity within Git projects. Therefore, we are interested in integrating with Micrometer to offer Java users a comprehensive and streamlined monitoring solution. This integration would also contribute to enhancing the impact of both our products.

We understand the concerns you raised in pr#3856, and they are indeed valid. To address them, we are happy to offer complimentary training and technical support to assist you in gaining a deeper understanding of DolphinDB.

Allow me to provide a brief introduction to DolphinDB: it is a distributed time-series database known for its powerful data analysis capabilities. It seamlessly combines batch and streaming processing. Currently, DolphinDB ranks 6th in the DBENGINES Time Series ranking. You can find the official documentation at the following address: Here is the official documentation address: https://github.com/dolphindb/Tutorials_EN

**Comment by shakuzen** [comment]
@peeyee Thank you for the explanation and the offer to help. For the reasons I mentioned previously, I still think that it will be better to maintain this registry implementation outside of the Micrometer repository. Even if the code lives in another source code repository such as https://github.com/liuwb2001/micrometer-registry-dolphindb, from the usage perspective, it will be the same for users: they add the dependency to their project and then they can use the DolphinDBMeterRegistry. If users have any Micrometer issues related to the integration, the Micrometer team is happy to help as best we can. We appreciate the effort on your part on this integration and I'm sorry we can't take on maintenance of the integration here.

**Pull request closed without merging**
