### PR TITLE
Support running docker in tests on CircleCI build

### PR DESCRIPTION
**Pull request by shakuzen**
We want to use Testcontainers for testing various functionality with real backends running. We need to run such tests on a `machine` type executor on CircleCI. This makes a separate CircleCI job to run those, using a newly added Gradle task `dockerTest` that only runs the tests tagged (with JUnit Jupiter's `@Tag("docker")`) with the `docker` label (see [sample test](https://github.com/micrometer-metrics/micrometer/pull/1837/files/d24244d4f8238de72acc6c3b6d98df891aba4631#diff-4d99805b0f2aec647c408ab8c1a1f0e5)). The default `test` task will not run the tests tagged with `docker`.

Unblocks things like #1429

Also upgrades to CircleCI's version 2.1 configuration which allows some deduplication of the executor, which was in order as different build images were being used in different jobs (by mistake). Also dedups the almost identical steps used in both the `build` and `docker-test` jobs.

### CODE REVIEW

**Comment by shakuzen** [comment]
Well, that didn't work at all (as mentioned in https://github.com/testcontainers/testcontainers-java/issues/1014#issuecomment-492872176). I'm going to take a new approach of using a JUnit Jupiter tag for tests that need docker support and excluding them from the default run. I'll make a separate `machine` executor that runs the docker tests in parallel. This will make it nicer for those building locally that don't have docker installed/running and for parallelizing the running of docker tests, which inherently have some extra overhead.

**Comment by shakuzen** [comment]
This seems to be working well. Only thing to maybe look into later is getting the `docker-test` job to run faster. It takes longer than the build that runs thousands of tests when it's only running 1 test. See https://circleci.com/workflow-run/892f1433-6a71-4b02-bdc6-da968442f3d9

I will update the pull request to remove the placeholder test tagged with `@Tag("docker")` which was only there to ensure this worked.

Please take a look @izeye and @jeqo. Let me know what you think, since you both have a pull request blocked by not being able to use testcontainers on our CI build.

**Comment by izeye** [comment]
@shakuzen Looks good to me, too. Thanks!

**Comment by shakuzen** [comment]
Thanks for the review. Let me know if you have any issues or feedback after rebasing your PRs on this post-merge.

**Pull request merged**
