### PR TITLE
Polish GraphiteMeterRegistry

### PR DESCRIPTION
**Pull request by izeye**
This PR polishes `GraphiteMeterRegistry`.

### CODE REVIEW

**Comment by izeye** [comment]
I created this against the `1.0.x` branch but can see the assigned milestone is "1.1.0-rc.1". The reason I created this against the `1.0.x` branch was to reduce chances to conflict when merging changes forward to the `master` branch. This is just a cosmetic change, so this can go either way if there's no concern on merging.

@jkschneider Do you prefer to make a change like this (a cosmetic one) against the `master` branch over the `1.0.x` branch?

**Comment by jkschneider** [comment]
> The reason I created this against the 1.0.x branch was to reduce chances to conflict when merging changes forward to the master branch.

You're probably right. I assigned to 1.1.0-rc.1 for the same reason. Lot to do for RC1, so the chance of merge conflict on this taking up time is why I haven't yet merged this.

**Comment by izeye** [comment]
@jkschneider Thanks for the clarification! I'm okay with either way. Just let me know if the target branch needs to be switched.

**Comment by mweirauch** [comment]
Sorry @izeye for breaking this.

**Comment by izeye** [comment]
@mweirauch Thanks for the review! I just rebased this onto the current `1.0.x` branch.

**Comment by izeye** [comment]
I just rebased this onto the current `1.0.x` branch and also changed to comply with the `this` keyword convention.

**Pull request merged**
