### PR TITLE
Update jooq to 3.14.+

### LINKED ISSUE #2304: Support jOOQ 3.14
See https://github.com/micrometer-metrics/micrometer/pull/2303

### PR DESCRIPTION
**Pull request by genuss**
This PR closes #2304 
Just updating dependency and implementing new methods with removing of `close` method.

### CODE REVIEW

**Comment by jkschneider** [comment]
Thanks @genuss !

**Comment by pivotal-issuemaster** [comment]
@genuss Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=2358)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=2358) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@genuss Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=2358)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=2358) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@genuss Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=2358)!

**Pull request merged**
