### PR TITLE
Use debug log level for successful metrics sent events.

### PR DESCRIPTION
**Pull request by izeye**
This PR changes the log level for successful metrics sent event to debug to lower verbosity by default.

### CODE REVIEW

**Comment by jkschneider** [comment]
We've consistently done info level for this same message in all the implementations. Should it be changed elsewhere as well?

Is log level purely subjective, or do you have a guiding principal in mind? Like a good sheep, I just followed the log level I saw in existing instrumentation (e.g. Spectator).

**Comment by izeye** [comment]
@jkschneider Sorry, I didn't notice that the log messages are consistent across all the implementations. When I ran a sample, I just noticed that showing the successful metrics sent events is a bit verbose as a default. I just thought we could assume everything's fine unless there's no warning or error. This might be subjective, so if you disagree with a good reason, feel free to close this one.

**Comment by jkschneider** [comment]
I don't have a strong opinion either way, but I've heard nothing but complaints about the verbosity level. So let's change them to debug 👍.

Example in the last comment on #790.

**Comment by shakuzen** [comment]
For the record: I'm 👍 on switching to DEBUG log level for successful metrics publish because INFO seems too verbose for a normal event in a metrics aspect of an application. I would have already suggested as much if I were using an implementation that published, but I'm using prometheus, so I didn't encounter this.

**Comment by dhaval24** [comment]
Debug makes a whole lot of sense. Specifically in prod excessive logs can be really irritating and also a hit on perf.

**Comment by izeye** [comment]
@jkschneider @shakuzen @dhaval24 Thanks for the feedback! I changed all existing info-level logging to be debug-level and to use consistent messages. I also changed the target branch to `master` as @jkschneider has set the target milestone to the "1.1.0-rc.1".

**Comment by izeye** [comment]
I resolved conflicts and rebased onto the current master branch.

**Comment by izeye** [comment]
I added the same log for Wavefront proxy in e74e9b2e788e08e870e8461a8c15c59cba75c105 as the following argument from @scottmf in https://github.com/micrometer-metrics/micrometer/issues/790#issuecomment-413946714 seems valid to me:

> I saw that while the directApi outputs some useful information the proxy does not. Not sure why that is but it seems reasonable to sync that up.

**Comment by jkschneider** [comment]
Thanks for your patience @izeye. Just wanted to get that `HttpClient` interface in first before considering this.

**Pull request merged**
