### PR TITLE
Auto-configure DiskSpaceMetrics

### PR DESCRIPTION
**Pull request by izeye**
This PR auto-configures `DiskSpaceMetrics`.

### CODE REVIEW

**Comment by jkschneider** [comment]
I'm going to hold off on this just temporarily until I have a chance to review what the default Netflix alerts were for disk utilization. It may lead to another disk binder that is more appropriate for autoconfiguration.

**Comment by izeye** [comment]
I rebased onto the current `master` to resolve conflicts.

**Comment by jkschneider** [comment]
Going to have to move this to 1.2.0. I still think it's likely `DiskSpaceMetrics` needs to be revised before 1.0 GA and we'll miss the Boot 2.1 RC cutoff for introducing additional autoconfigs.

**Comment by izeye** [comment]
Closing as the `micrometer-spring-legacy` module has been removed since Micrometer 1.4.0 via https://github.com/micrometer-metrics/micrometer/issues/1662.

**Pull request closed without merging**
