### PR TITLE
Start line sink only when enabled in StatsD meter registry

### PR DESCRIPTION
**Pull request by izeye**
This PR changes to start line sink only when enabled in StatsD meter registry.

### CODE REVIEW

**Comment by izeye** [comment]
For reviews, see https://github.com/micrometer-metrics/micrometer/pull/1260/files?w=1

**Comment by shakuzen** [comment]
I decided to write a test for this (see e258b0d4629b9c3c988dde9ad11a248420dfa70b) and then realized that the line sink wouldn't actually be called before either due to

```java
@Override
public void onNext(String line) {
    if (started.get()) {
        lineSink.accept(line);
    }
}
```

The test is actually failing now due to the assertion that the queue gets drained. When the registry is disabled, it seems the queue will continue to grow since nothing is subscribed. This is a (big) problem.

**Comment by izeye** [comment]
@shakuzen Thanks for adding the test and spotting the problem! Are you working on it? Otherwise, I can try to resolve it.

**Comment by izeye** [comment]
@shakuzen I created #1263 to try to resolve it just in case. If you already have a fix for it locally, feel free to close it.

**Pull request merged**
