### PR TITLE
Update samples to Spring Boot 2.7.18

### PR DESCRIPTION
**Pull request by izeye**
This PR updates samples to Spring Boot 2.7.18.

### CODE REVIEW

**Comment by izeye** [comment]
Dependabot [handles Gradle Enterprise Gradle plugin](https://github.com/micrometer-metrics/micrometer/pull/4109) but doesn't seem to handle other Gradle plugins like this and https://github.com/micrometer-metrics/micrometer/pull/4410.

**Comment by shakuzen** [comment]
Unfortunately dependabot's support of the Java ecosystem and Gradle is limited in multiple ways. This might be another such limitation. It may work if we migrate the plugin declaration to reference something in the toml version catalog.

**Comment by shakuzen** [comment]
That said, in regards to the spring samples, I think we should rather work to remove them from the micrometer repo and make sure anything we want covered is included in the micrometer-samples or other repo. Having them in the micrometer repo makes a circular dependency, which isn't the end of the world for a sample, but it's also unnecessary if we can do the same thing in a samples repo.

**Comment by jonatan-ivanov** [comment]
Let me merge this so that we are using the latest version and then we can move them to the samples repo.

**Comment by jonatan-ivanov** [comment]
Thank you!

**Pull request merged**
