### PR TITLE
StepCounter does not push incomplete step values on application shutdown

### PR DESCRIPTION
**Pull request by garridobarrera**
Hi guys, I have created this pull request to attempt solve the problem discussed in the issue #1882
@izeye @shakuzen @jkschneider

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@garridobarrera Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=2519)!

[Click here](https://cla.pivotal.io/sync/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=2519) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@garridobarrera Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/pivotal?repositoryId=micrometer-metrics/micrometer&pullRequestId=2519)!

**Comment by ajs1998** [comment]
I would love to see this issue fixed.
We're using Micrometer in Google's managed Cloud Run. Instances spin up and shut down all the time, and Google even accelerates instance shutdown if multiple requests return 5xx codes. So we get flaky metric reporting on buggy services, which is the worst time to be experiencing flaky metrics.

**Comment by joshua-paypay** [comment]
Hi I am also having the same issue. Are there any pending action items on this PR?

**Comment by joshua-paypay** [comment]
I guess this PR is not completed. @garridobarrera are you still working on this PR? I am also facing this issue and was doing some research on this. Can I continue to work on it? Thanks.

**Comment by jonatan-ivanov** [comment]
@garridobarrera I'm looking into this and I'm thinking probably propagating the "getting the current value" functionality even deeper than the Meter level (`StepTuple2` `StepValue`, `TimeWindowMax`) and also add this capability to every step registry.

Are you interested in contribution on this? If so, as the first step, could you please rebase your changes to `1.8` since that is the lowest version we support right now.

**Comment by shakuzen** [comment]
@garridobarrera thank you very much for the pull request. Ultimately, we went with a different approach in #3681, which should require less (or no) changes in each registry implementation that extends StepMeterRegistry. It should have the same effect as these changes, but for most step based registries. Please do give it a try (it will be released shortly in milestone 1.11.0-M2) and let us know if you have any thoughts on the approach taken there.

**Pull request closed without merging**
