### PR TITLE
Prevent publishing NaN or infinite values to AppOptics

### PR DESCRIPTION
**Pull request by izeye**
This PR prevents publishing NaN or infinite values to AppOptics.

Closes gh-1108

### CODE REVIEW

**Comment by jkschneider** [comment]
Note to self: rebase on 1.1.x before merging.

**Comment by izeye** [comment]
@jkschneider Sorry, I forgot to change the target branch. Now I changed it to the 1.1.x branch.

**Comment by jkschneider** [comment]
I suppose we'll need to delete the dependency lock changes on the 1.1.x branch.

**Comment by izeye** [comment]
@jkschneider The failing CI task was `downloadDependencies` which I didn't run locally, and I updated dependency locks for it. Now the CI build seems to be okay although I don't understand the root cause of it in the first place. I think it'd be better to include the depedency lock updates to satisfy Gradle unless there's any other way to make it happy.

**Comment by izeye** [comment]
FTR I thought the dependency lock problem happens only in Gradle 5.0 but it also happens in [Gradle 4.10.2 which the 1.1.x branch uses](https://github.com/micrometer-metrics/micrometer/blob/1.1.x/build.gradle#L100) although I'm not sure it's a bug or a feature which I don't know.

**Comment by jkschneider** [comment]
I see, a patch upgrade of Spring Boot, from which I suppose the rhino dependency is derived transitively.

**Pull request merged**
