### PR TITLE
Add type data to datadog API calls

### PR DESCRIPTION
**Pull request by checketts**
Addresses #288 

@khelenek I'm not too familiar with [Datadog metric types](https://help.datadoghq.com/hc/en-us/articles/206955236-Metric-types-in-Datadog). 

Could you please hep answer if `count` or `gauge` is sufficient? I'm not certain when a `rate` would be appropriate.

### CODE REVIEW

**Comment by checketts** [comment]
I also added `unit`, But that isn't clear if that is part of the input json, based on the docs.

**Comment by khelenek** [comment]
Much appreciated the quick turnaround. I added a note to the issue: I'm not entirely sure it's possible to control this through the API; the docs seem to suggest that any metric through the API gets created as a Gauge type. I apologize that I did not include that I was using the HTTP method, not the statsd/agent method. I did not test with the agent. Did you solve using the HTTP method, or did you also discover it affected the agent method?

I am also uncertain on when rate would be more appropriate, but counter vs gauge seems to me the most important distinction.

**Comment by checketts** [comment]
This is for the HTTP API. Since it allows the type to be passed, it seems like this PR will fix it.

What are the tradeoffs right now with metrics appearing as a gauge instead of count? Does it limit which functions can be used with it? Or just exposes it incorrectly in the the explorer?

**Comment by khelenek** [comment]
Yeah it affects the usage, not just the categorization. For a gauge you can't do things like total count for the last hour/day/etc. It treats it more like a sampling of the data at that time.

**Comment by jkschneider** [comment]
Merged with 489f13fabcaaba5c872a4fe874fccb91d33f3d4c

**Pull request closed without merging**
