### PR TITLE
Exemplars support for Prometheus Counter

### PR DESCRIPTION
**Pull request by jonatan-ivanov**
fixes gh-2811

### CODE REVIEW

**Comment by fscellos** [comment]
Hello @jonatan-ivanov , as i comment in #2812, it is necessary to take account sampled trace flags (https://www.w3.org/TR/trace-context/#sampled-flag) to be sure that the trace_id set in exemplars will be effectively recorded in backend storage.

**Comment by fscellos** [comment]
Hello, this is doable with OpenTelemetry API (Span.current().getSpanContext().getTraceFlags().isSampled()). 
To use it, i think we must implement and use Samplers (ExemplarSampler) that take this information into account no new Examplar is this data is not set to true).
I will try.

**Comment by jonatan-ivanov** [comment]
@fscellos That would be the responsibility of the implementation of the `SpanContextSupplier` that we are not providing here.

**Comment by fscellos** [comment]
I create an issue on prometheus client for this case : https://github.com/prometheus/client_java/issues/765

**Review by shakuzen — APPROVED** [review]

**Pull request merged**
