### PR TITLE
Seperate _max metric of histograms and summaries to gauge

### PR DESCRIPTION
**Pull request by marcoschulte**
Fix for #519

### CODE REVIEW

**Comment by mweirauch** [comment]
The scaling of the `_max` timeunit is off. Haven't looked at the code, yet.

```
http_server_requests_seconds_count{application="micrometered",exception="None",method="GET",status="200",uri="/jersey/hello/{name}",} 1.0
http_server_requests_seconds_sum{application="micrometered",exception="None",method="GET",status="200",uri="/jersey/hello/{name}",} 0.038140035
# HELP http_server_requests_seconds_max  
# TYPE http_server_requests_seconds_max gauge
http_server_requests_seconds_max{application="micrometered",exception="None",method="GET",status="200",uri="/jersey/hello/{name}",} 3.8140035E7
```

**Comment by jkschneider** [comment]
Merged with 5fbaa762afd71b5091e16e165f008ba1e1fe0c18 and 81633289f222861eb2a80faeca153ddb8b5d799b.

**Comment by mweirauch** [comment]
I've pushed a correcting commit to your repo/PR.
I made the tests use some more distinct values and check the full value of the scraped line.

**Comment by mweirauch** [comment]
@jkschneider and me collided a bit with the fixes. @marcoschulte you might wan't to reset on origin/master on your repo in case you'd like to contribute further. Sorry for the confusion and thanks for this contribution!

**Pull request closed without merging**
