### PR TITLE
 Make index template compatible with Elasticsearch 7

### PR DESCRIPTION
**Pull request by izeye**
This PR changes to make the index template compatible with Elasticsearch 7 by removing usages of [`_default` mapping](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/default-mapping.html) and [`_all` field](https://www.elastic.co/guide/en/elasticsearch/reference/6.8/mapping-all-field.html) which have been deprecated since Elasticsearch 6 and removed in Elasticsearch 7.

This change affects only with Elasticsearch 7 or later and Elasticsearch 6 or prior will remain as-is.

I've tested this change against Elasticsearch 7 (7.0.1), 6 (6.7.2), and 5 (5.6.15).

This change has been built on top of #1427 as it's necessary to get the version of Elasticsearch.

Closes gh-1408

### CODE REVIEW

**Comment by shakuzen** [comment]
@izeye what do you think about setting up some integration tests with testcontainers so we can ensure via CI that this works with all the versions we say? https://www.testcontainers.org/modules/elasticsearch/
Of course, we can make a separate issue for it so as not to block this, but it made me think it is probably time we integration test this.

**Comment by izeye** [comment]
@shakuzen Sounds great and I'd like to but I'm not familiar with it, so it might take some time for me. I think it'd be good to have a separate issue for it. If you're already familiar with it, giving me some direction could boost the progress. Or you could do it yourself if you prefer.

**Comment by izeye** [comment]
I rebased this onto the current 1.1.x branch having #1427.

**Comment by izeye** [comment]
@shakuzen Sorry, I missed authentication part for Elasticsearch version fetching. I'll create a fix for it shortly.

**Pull request merged**
