### PR TITLE
Clean up notification listeners in TomcatMetrics

### LINKED ISSUE #1424: ClassLoader leak in TomcatMetrics
When a web application is deployed multiple times, the old classloader will not be garbage collected. This is similar to #827 

I debugged with eclipse and see the following behaviour:
registerMetricsEventually will be called 2x (for "type", "StringCache" and "j2eeType", "Servlet") but on redeploy, the listener, which removes itself with `mBeanServer.removeNotificationListener` is only called for the "j2eeType", "Servlet" filter. 
You see also in the debug screenshot, that there are more than one "type", "StringCache" refenece in the listenerList.

Tomcat version is 9.0.20 (tested on windows)
 
Possible fix: Let TomcatMetrics implement DisposableBean and remove all listeners on destroy.

(Is there a simple workaround to disable the TomcatMetrics?)

jprofiler
grafik

eclipse debug
grafik

### PR DESCRIPTION
**Pull request by izeye**
This PR changes `TomcatMetrics` to implement `AutoCloseable` to clean up notification listeners.

Closes #1424

### CODE REVIEW

**Comment by jkschneider** [comment]
@izeye All the `MeterBinder` implementations used to implement `AutoCloseable`, but we had some feedback a while back that it makes for a bad IDE experience, because the block of code that creates the binder isn't usually what closes it, and Intellisense expects a try-with-resources block or explicit close call.

**Comment by izeye** [comment]
@jkschneider Thanks for the feedback! The reason why I thought that implementing `AutoCloseable` was reasonable is that the clean-up method needs to be called explicitly. If a static code analysis tool warns on this, it sounds like a false positive to me.

**Comment by shakuzen** [comment]
Perhaps having a close method without implementing `AutoCloseable` is a reasonable compromise. We can explain in the JavaDoc for the class when a user of the class wants to ensure the close method is called.

**Comment by shakuzen** [comment]
Providing a clean up method is a good idea, but I wonder if we are also registering listeners for things that will never be notified. If we can eliminate that, it would help with memory usage, even in the case where there aren't multiple contexts. We can tackle that in a separate change, though.

**Comment by izeye** [comment]
> Perhaps having a close method without implementing `AutoCloseable` is a reasonable compromise.

@shakuzen Thanks for the feedback!

We already have four `MeterBinder`s implementing `AutoCloseable` (`JvmGcMetrics`, `KafkaConsumerMetrics`, `Log4j2Metrics`, and `LogbackMetrics`). Do we want to apply the same rule for them?

**Comment by izeye** [comment]
> Providing a clean up method is a good idea, but I wonder if we are also registering listeners for things that will never be notified.

@shakuzen I thought about it, but I didn't do it intentionally as it is a breaking change. Is it okay to remove it on master?

**Comment by shakuzen** [comment]
For reference, here are the previous issues that have been raised for IDE/Sonar warnings on things that are `AutoCloseable`: #1492 and #757.

> We already have four `MeterBinder`s implementing `AutoCloseable` (`JvmGcMetrics`, `KafkaConsumerMetrics`, `Log4j2Metrics`, and `LogbackMetrics`). Do we want to apply the same rule for them?

I forgot about those. It is probably better to be consistent. I'm leaning towards making `TomcatMetrics` `AutoCloseable`, but I'm open to other proposals also.

**Pull request merged**
