### PR TITLE
Use JUnit Jupiter for JerseyTest tests

### PR DESCRIPTION
**Pull request by izeye**
This PR changes to use JUnit Jupiter for `JerseyTest` tests as https://github.com/eclipse-ee4j/jersey/issues/3662 seems to be resolved via https://github.com/eclipse-ee4j/jersey/pull/4824 since 2.35.

This PR also removes dependency management for JUnit 4 as it's not used anymore.

### CODE REVIEW

**Review by jonatan-ivanov — APPROVED** [review]
I'm going to rebase this to `1.8.x`

**Comment by jonatan-ivanov** [comment]
Committed in https://github.com/micrometer-metrics/micrometer/commit/e05f3e56d42eedafe2ab530708799962144c095a

Thank you very much!

**Comment by izeye** [comment]
@jonatan-ivanov Thanks!

This isn't a user-facing change, so the `type: task` label seems to be more appropriate than the `enhancement` one, especially considering the way of generating release notes.

**Comment by jonatan-ivanov** [comment]
Yepp, you are right, thank you!

**Comment by mweirauch** [comment]
Thanks for taking care of this! I was watching the original issue, but there was no activity, yet.

**Pull request closed without merging**
