### PR TITLE
Polish MeterFilter

### PR DESCRIPTION
**Pull request by izeye**
This PR polishes `MeterFilter`.

### CODE REVIEW

**Comment by izeye** [comment]
@shakuzen Oops, I meant to create this against the 1.0.x branch but accidentally created against the `master` branch.

**Comment by izeye** [comment]
@shakuzen Is it better to create another against the 1.0.x branch or just leaving it as it is on the 1.0.x branch?

**Comment by shakuzen** [comment]
Feel free to make another pull request to 1.0.x. Otherwise, I can backport the changes to 1.0.x.

**Comment by izeye** [comment]
@shakuzen Thanks for the quick feedback! I created https://github.com/micrometer-metrics/micrometer/pull/1365.

**Pull request merged**
