### PR TITLE
Correctly set initial value for jvm.gc.max.data.size

### PR DESCRIPTION
**Pull request by danieljamesscott**
Fix for https://github.com/micrometer-metrics/micrometer/issues/1678

### CODE REVIEW

**Comment by danieljamesscott** [comment]
I have no idea what caused that build failure - I didn't change anything related to that. Can someone help?

**Comment by shakuzen** [comment]
> I have no idea what caused that build failure - I didn't change anything related to that. Can someone help?

I'm looking into it. It looks like it is caused by the recently released Hazelcast 4.0-BETA-1. I'll fix it on master and then you can rebase to rebuild with the fix.

**Comment by danieljamesscott** [comment]
Thanks - I was just coming to that conclusion myself: https://mvnrepository.com/artifact/com.hazelcast/hazelcast/4.0-BETA-1

Weird that the `latest.release` includes one marked 'BETA'. :)

**Comment by shakuzen** [comment]
> Weird that the `latest.release` includes one marked 'BETA'. :)

I agree. It'd be nice if Gradle could recognize pre-release versions. On the other hand, this is one of the reasons we use `latest.release` on `master` without dependency locks - to recognize these kinds of incompatibilities as soon as possible. We can now track supporting the new version. Unfortunately, it does cause these kinds of interruptions to contributions.

I have fixed `master` by pinning to Hazelcast 3 for now. So you can rebase your pull request on the latest master.

**Comment by danieljamesscott** [comment]
OK, thanks. I've rebased from latest master and the tests are now passing (After I fixed a couple of license violations).

**Comment by jkschneider** [comment]
LGTM, thanks for the fix @danieljamesscott!

**Comment by jkschneider** [comment]
Also cherry-picked onto 1.3.x with 8b2893e0.

**Pull request merged**
