### PR TITLE
Restore TCP connection when disconnected in StatsD meter registry

### PR DESCRIPTION
**Pull request by izeye**
This PR changes to restore TCP connection when disconnected in StatsD meter registry.

Closes gh-1212

### CODE REVIEW

**Comment by izeye** [comment]
@shakuzen Thanks for the feedback! I checked it's working in a sample with a simple `Flux` and just applied the change to it but should have tested it again with the registry implementation. It doesn't seem to work with `bufferingPublisher` (or other culprit, I'm not sure ATM). I'll look into it with a proper test(s).

**Comment by jkschneider** [comment]
Should this be a 1.1.4 fix?

**Comment by izeye** [comment]
@jkschneider Based on #1009, the TCP support for the StatsD meter registry will be introduced in 1.2.0.

**Comment by izeye** [comment]
The failure was due to the following exception:

```
java.lang.IllegalStateException: UnicastProcessor allows only a single Subscriber
	at reactor.core.publisher.UnicastProcessor.subscribe(UnicastProcessor.java:430)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
	at io.micrometer.statsd.internal.LogbackMetricsSuppressingUnicastProcessor.subscribe(LogbackMetricsSuppressingUnicastProcessor.java:33)
	at reactor.core.publisher.FluxSource.subscribe(FluxSource.java:52)
	at reactor.core.publisher.FluxPeek.subscribe(FluxPeek.java:83)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onNext(FluxFlatMap.java:389)
	at reactor.core.publisher.FluxArray$ArraySubscription.slowPath(FluxArray.java:126)
	at reactor.core.publisher.FluxArray$ArraySubscription.request(FluxArray.java:99)
	at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:335)
	at reactor.core.publisher.FluxMerge.subscribe(FluxMerge.java:69)
	at reactor.core.publisher.FluxBufferPredicate.subscribe(FluxBufferPredicate.java:95)
	at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:62)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
	at reactor.core.publisher.FluxOnBackpressureLatest.subscribe(FluxOnBackpressureLatest.java:43)
	at reactor.core.publisher.FluxMap.subscribe(FluxMap.java:62)
	at reactor.netty.FutureMono$1.subscribe(FutureMono.java:141)
	at reactor.core.publisher.Flux.subscribe(Flux.java:7777)
	at reactor.netty.channel.ChannelOperationsHandler.drain(ChannelOperationsHandler.java:460)
	at reactor.netty.channel.ChannelOperationsHandler.flush(ChannelOperationsHandler.java:194)
	at io.netty.channel.AbstractChannelHandlerContext.invokeFlush0(AbstractChannelHandlerContext.java:776)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:802)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1031)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:309)
	at reactor.netty.FutureMono$DeferredWriteMono.subscribe(FutureMono.java:323)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3694)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.netty.tcp.TcpClient.lambda$handle$3(TcpClient.java:314)
	at reactor.netty.tcp.TcpClientDoOn.onStateChange(TcpClientDoOn.java:66)
	at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:358)
	at reactor.netty.resources.NewConnectionProvider$NewConnectionObserver.onStateChange(NewConnectionProvider.java:205)
	at reactor.netty.channel.ChannelOperationsHandler.channelActive(ChannelOperationsHandler.java:112)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelActive(AbstractChannelHandlerContext.java:192)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelActive(DefaultChannelPipeline.java:1396)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:213)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelActive(AbstractChannelHandlerContext.java:199)
	at io.netty.channel.DefaultChannelPipeline.fireChannelActive(DefaultChannelPipeline.java:906)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:311)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:341)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:665)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:612)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:529)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:491)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905)
	at java.lang.Thread.run(Thread.java:748)
```

I couldn't find an easy fix for this at the moment. Any help would be appreciated.

**Comment by shakuzen** [comment]
I'm no Reactor (much less Reactor Netty) expert but it seems `UnicastProcessor allows only a single Subscriber` means we are making a new subscriber to the `bufferingPublisher` when reconnecting. In that case, we need to somehow cancel/complete the previous subscription before reconnecting, I guess. If we can't figure this out, we can reach out to the Reactor Netty team for help.

**Comment by izeye** [comment]
@shakuzen Thanks for the feedback! AFAICT there's no way to unsubscribe for `UnicastProcessor`. I might miss something as I don't have much expertise on Reactor or Reactor Netty, either.

**Comment by benzaita** [comment]
> If we can't figure this out, we can reach out to the Reactor Netty team for help.

@smaldini @violetagg maybe you can help?

> we need to somehow cancel/complete the previous [UnicastProcessor] subscription before reconnecting

**Comment by codeperfector** [comment]
@izeye @benzaita Any updates on this issue?

**Comment by sdemart-rei** [comment]
Any updates on this bug? We've run into it on our servers and I would love to help dig in to get it worked out if needed

**Comment by benzaita** [comment]
If you are running on AWS, it might be worth to migrate to UDP, now that their ALB supports UDP.

**Comment by sdemart-rei** [comment]
Yeah we already have plans to do that for stuff that we can, but we have other servers that are not in AWS that still need TCP for now.

**Comment by shakuzen** [comment]
I've dug into this for a bit and I'm trying to make sure we're clear on what capabilities there are currently, so any changes we make to fix this currently broken feature (TCP reconnect) don't affect other capabilities. To fix reconnect, we will not be able to continue using a `UnicastProcessor` underneath due to the aforementioned limitations (only one consumer ever allowed).

### Current state:
We should add any missing tests for anything that is intentional.
* TCP & UDP: if initial connection fails (e.g. statsd daemon is down) when application starts, there will be no subscriber to the processor, so all statsd lines will be dropped for the life of the application.
* TCP & UDP: if connection is terminated while the application is running (e.g. statsd daemon goes down), it will not be re-established, and all statsd lines will be dropped from that point.
* buffered TCP & UDP: if sending is slower than buffering, `onBackpressureLatest` will keep the most recent set of buffered lines but drop any emitted in between.

In testing, I notice we don't have any logging for the above scenarios, but that is a separate issue.

I'm not sure unbuffered TCP is even working, at least in my testing with a local statsd daemon and Etsy flavor. If I use `nc -l 8125` I can see the lines sent, but for some reason the statsd daemon is not accepting these or recognizing them as bad lines either.

The queue used by the `UnicastProcessor` has been an issue in the past (#462), but this only comes into play when buffering is turned off (not the default anymore) and the UdpClient/TcpClient cannot keep up with sending the statsd lines.

### Desired state:
I'm not sure there is any reason for a reconnect feature to be specific to TCP, so we could probably do it for UDP also. That said, we have never had reconnect as far as I can tell, so I've changed this from a `bug` to an `enhancement` and accordingly changed it to target the upcoming feature release `1.3.0`.

While the changes to support this won't affect configuration or setup from a user perspective, internals may be significantly different, so I want to ensure we have time for testing of snapshots by users.

After this, the behavior should be that connection failures are retried (both initial connection failures and failures during the application's life).

**Comment by shakuzen** [comment]
I've added in the changes from here to #1782 and will try to add a test for it there as well. The changes to the `Processor` we were using was necessary to reconnect, as mentioned previously here.

**Pull request closed without merging**
