### PR TITLE
support tcp protocol in statsd exporter

### PR DESCRIPTION
**Pull request by psycho-ir**
Some statsd agents like `Telegraf` support TCP protocol as well and we do use it to gather our metrics, So I opened this PR to add possibility to chose the agent's protocol.

Please do let me know if anything is missing.

### CODE REVIEW

**Comment by jkschneider** [comment]
Thanks for the effort @psycho-ir! There are some minor unnecessary whitespace formatting that was done in the PR, but the implementation looks solid.

**Comment by psycho-ir** [comment]
Hi @jkschneider, 

Thanks for the response. 
Right, I guess my IDE didn't respect the `.editorconfig`. 
I'll fix the format tomorrow.

**Comment by behdadkh** [comment]
Cool! Just what I was looking for! Thanks.

**Comment by jkschneider** [comment]
@psycho-ir I think I don't see the `.editorconfig` problem based on my IDE setup. Would welcome a PR to fix that.

**Pull request merged**
