### PR TITLE
Improve partial error logging for Elasticsearch meter registry

### PR DESCRIPTION
**Pull request by izeye**
When the HTTP status is considered as success but its body has `errors` property, there's no logging for request body unlike unsuccessful HTTP statuses. This PR changes to log HTTP request errors in Elasticsearch meter registry consistently.

### CODE REVIEW

**Comment by shakuzen** [comment]
Are you aware of Elasticsearch documentation on this? I would like to understand if they have documented differences of when Elasticsearch will return an unsuccessful status code versus a successful status code with an unsuccessful body.

**Comment by izeye** [comment]
@shakuzen I didn't find any doc on it but when I was looking into #1071 I noticed the `errors` property has been set when there's partial failure of a bulk request.

With regards to the `error` property case I'd like to change the log message to show numbers for both successes and failures as the current message seems to indicate a total failure. If you agree with this, I can update this PR or prepare another one for it.

**Comment by shakuzen** [comment]
> I didn't find any doc on it but when I was looking into #1071 I noticed the `errors` property has been set when there's partial failure of a bulk request.
> 
> With regards to the `error` property case I'd like to change the log message to show numbers for both successes and failures as the current message seems to indicate a total failure. If you agree with this, I can update this PR or prepare another one for it.

Yes that seems to make sense. Otherwise partial failures and complete failures might look the same.

**Comment by izeye** [comment]
@shakuzen Thanks for the feedback!

> If you agree with this, I can update this PR or prepare another one for it.

Is it okay to update this PR accordingly?

**Comment by shakuzen** [comment]
> Is it okay to update this PR accordingly?

Yes, please.

**Comment by izeye** [comment]
@shakuzen I updated as discussed.

**Pull request merged**
