### PR TITLE
Don't overwrite reserved resource attributes

### PR DESCRIPTION
**Pull request by zeitlinger**

### CODE REVIEW

**Comment by marcingrzejszczak** [comment]
Hey @zeitlinger , is there a corresponding issue for this PR?

**Comment by zeitlinger** [comment]
> Hey @zeitlinger , is there a corresponding issue for this PR?

No, I just ran into this issue here: https://github.com/grafana/grafana-opentelemetry-starter/pull/56/files#diff-a07822eb18120c3511dcf168121285de5ae34cd60b00812144db178aadb7e1b9R20

**Review by marcingrzejszczak — APPROVED** [review]
WDYT @shakuzen @jonatan-ivanov ?

**Review by shakuzen — APPROVED** [review]
Thanks for the enhancement!

**Pull request merged**
