### PR TITLE
Use SessionFactory for public static factory methods and constructor

### PR DESCRIPTION
**Pull request by izeye**
Closes gh-1037

/cc @snicoll

### CODE REVIEW

**Comment by snicoll** [comment]
@izeye thanks for the poing. Have you considered wrapping the call to hibernate in a static class that we would wrap with a class presence check? IMO, if the input of this class is the JPA interface, we ought to be a bit more defensive about things.

**Comment by izeye** [comment]
@snicoll Thanks for the feedback! I just chose this approach as its implementation seems to assume that Hibernate is on the classpath and Hibernate will be on the classpath in most cases, so I just thought clarifying it might be sufficient.

IIUC, the suggested approaches are as follows:

1. Make `HibernateMetrics` no-op when it's not on classpath.
2. Change parameter type `EntityManagerFactory` to `SessionFactory` on public static factory methods and constructor.

For the first approach, I'm not sure it's worthing allowing `HibernateMetrics` to be created when Hibernate isn't on the classpath as it will bring some code which doesn't seem to be neat.

For the second approach, I prefer this one but it's a breaking change, so I just hesitated to do so but it's a right way to go, I'm happy to update this PR to do so.

I might misunderstand the suggestions. Please correct me if I'm wrong.

**Comment by snicoll** [comment]
Thanks for the feedback. I prefer the second one as well but that ship has sailed for the current line.

> as it will bring some code which doesn't seem to be neat.

I am not sure I got that. I agree that `HibernateMetrics` means exactly that it is supposed to work with Hibernate but the fact the current arrangement allows you to create an instance without an Hibernate-specific construct is a case for making it more lenient. The fact we have to unwrap to `SessionFactory` is an implementation detail after all...

**Comment by izeye** [comment]
@snicoll Thanks for the quick feedback! "some code" meant code for hiding [the `stats` final member field typed `Statistics`](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/jpa/HibernateMetrics.java#L45) somehow to avoid `ClassNotFoundException`. I'll update this to the second approach.

**Comment by izeye** [comment]
@snicoll I've updated this to the second approach. Let me know it's what you have in mind.

**Pull request merged**
