### PR TITLE
Allow using TomcatMetrics without `Manager` on the compilation classpath

### PR DESCRIPTION
**Pull request by jjank**
See relevant Slack discussion: https://micrometer-metrics.slack.com/archives/C662HUJC9/p1698128026070889

EDIT: I've added Javadoc to the new constructors 👍

### CODE REVIEW

**Comment by jonatan-ivanov** [comment]
I tested this the following way:
1. Published it to my maven local: `./gradlew pTML`
2. Created an empty Gradle project using `gradle init`
3. Added `mavenLocal()` and `micrometer-core`
4. Wrote a psvm app

build.gradle
```gradle
apply plugin: 'java'

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation 'io.micrometer:micrometer-core:1.12.0-SNAPSHOT'
}
```

Demo.java
```java
MBeanServer mBeanServer = ManagementFactory.getPlatformMBeanServer();
MeterRegistry registry = new SimpleMeterRegistry();

try (TomcatMetrics tomcatMetrics = new TomcatMetrics(Tags.empty())) {
	tomcatMetrics.bindTo(registry);
}
try (TomcatMetrics tomcatMetrics = new TomcatMetrics(Tags.empty(), mBeanServer)) {
	tomcatMetrics.bindTo(registry);
}
```

The first ctor (`TomcatMetrics(Iterable<Tag>)`) goes through the compiler without any problems. The second one (`TomcatMetrics(Iterable<Tag>, MBeanServer)`) does not:
```
java: cannot access org.apache.catalina.Manager
  class file for org.apache.catalina.Manager not found
```

I guess because in the first case the compiler can decide which ctor to  call without looking into the others (one argument) while in the second case, it needs to look into the types. I think even if we add the first ctor, it can make this unsafe since future ctors we add can cause compile errors. For example if I add a one-arg ctor with the `Manager` (`TomcatMetrics(Manager)`), the first case above fails too with the same compiler error.

**Comment by jjank** [comment]
Hi @jonatan-ivanov,

my bad I guess I jumped to a conclusion to quickly 🙈 

I agree that it's not a safe option to add any of the two ctors. Additionally it's confusing because the class offers so many constructors.

The only alternative I could think of is static factory methods. Something along the lines of:
```java
public static TomcatMetrics forStandalone(Iterable<Tag> tags, MBeanServer mBeanServer) {
        return new TomcatMetrics(null, tags, mBeanServer);
    }

// It's debatable whether this method is _really_ necessary. Requring users to call `TomcatMetrics::getMBeanServer` seems reasonable
public static TomcatMetrics forStandalone(Iterable<Tag> tags) {
        return new TomcatMetrics(null, tags, getMBeanServer());
    }
```

This would solve some issues:
* Although `forStandalone` specifically is up for discussion but obviously there at least is a chance of naming
* Safer evolvment of the API

I've updated my PR with the static factory methods. But feel free to not accept the PR at all if you think it is not worth the extra API-surface

**Comment by jjank** [comment]
@jonatan-ivanov I've rebased my branch onto main, now the build passes 😅

**Comment by jonatan-ivanov** [comment]
As far as I remember we further discussed this on Slack and the conclusion was that if you add `org.apache.tomcat.embed:tomcat-embed-core` as a `provided` dependency (compile-only), you can reference the `Manager` class which will be provided by Tomcat runtime.

With that, let me close this PR. Also, we are planning to look into providing a JMX-fee/Manager-free implementation of `TomcatMetrics`, see:
- https://github.com/micrometer-metrics/micrometer/pull/1620
- https://github.com/micrometer-metrics/micrometer/issues/1433

Please let s know if my I didn't remember correctly and you want us to reopen this PR.

**Pull request closed without merging**
