### PR TITLE
Improve registering meters with single tag

### PR DESCRIPTION
**Pull request by maciejwalkowiak**
The goal of this PR is to improve registering metrics with single tag.

Currently there are two ways of registering metrics - lets take `Counter` as an example:

```java
meterRegistry.counter("message.received", "tagKey", "tagValue")
```
This method does not give compilation time safety - if number of `String` parameters passed as tags is not even then code will throw exception in runtime.

```java
metrics.counter("message.received", Arrays.asList(Tag.of("tagKey", "tagValue")))
```
This method adds extra boilerplate.

This PR simplifies it to:
```java
metrics.counter("message.received", Tag.of("tagKey", "tagValue"))
```
which guarantees compilation time safety and eliminates boilerplate.

I guess similar methods could/should be added to `Metrics` class.

### CODE REVIEW

**Comment by jkschneider** [comment]
@maciejwalkowiak I think you have a valid point about their being a gap.

WDYT about adding a signature to `Tags` like `singletonList(String key, String value)` that mirrors Java's `Collections#singletonList` instead? Then we wouldn't have to add additional signatures for all the different meter types?

**Comment by maciejwalkowiak** [comment]
The drawback of having this method in `Tags` is that library users will have to know that this method exist in order to use it - `Cmd+Space` will not suggest it to them. If we go this way I think the existence of such a method should be at least mentioned in the reference guide.

I am fine with both approaches, pick the one you prefer and I will adjust the PR.

**Comment by maciejwalkowiak** [comment]
I understand your concern about growing number of API methods. I was thinking if I am not making another `RestTemplate` kind of class while I was adding these methods. 

The alternative would be a fluent builder (similar to [QueueBuilder](https://github.com/spring-projects/spring-amqp/blob/master/spring-amqp/src/main/java/org/springframework/amqp/core/QueueBuilder.java) from Spring AMQP).

```
metrics.counter("my.counter")
       .tag("key1","value1")
       .tag("key2","value2")
       .build()
```

For *Gauges* it would make even bigger difference:

```
metrics.gauge("my.gauge")
       .tag("key1","value1")
       .obj(...)
       .func(...)  
       .build()
```

This would unfortunately break current API. Since it's already RC I guess it's too late for such changes.

I will go on with `Tags#singletonList`. It can be always improved later in the future.

**Comment by checketts** [comment]
I wish `singletonList` was shorter.

**Comment by maciejwalkowiak** [comment]
Do you mean the method name? I agree. How about `Tags.of(key, value)`?

**Comment by checketts** [comment]
`Tags.of(key, val)` is great! The `Tags` prefix implies it is plural.

**Comment by maciejwalkowiak** [comment]
I'll wait for @jkschneider. I guess he has a decision power here..?

**Comment by checketts** [comment]
>  I guess he has a decision power here..?

Absolute power ;)

**Comment by jkschneider** [comment]
> I guess he has a decision power here..?
Yikes! I guess it's more like I'll have to live with it ;)

> Tags.of(key, val) is great!
Sounds good to me.

**Comment by jkschneider** [comment]
Closed with d47b4df3da5371eb4ef76a674067b28ba522bd08. Thanks for the input @maciejwalkowiak!

**Comment by jkschneider** [comment]
@maciejwalkowiak Also, forgot to mention that there are already fluent builders for all the meter types:

```java
Gauge.builder("my.gauge")
   .tags("k", "v")
   .register(registry);
```

I could see value in going back to each builder and adding a `tag(String key, String value)` signature.

**Comment by maciejwalkowiak** [comment]
Thanks @jkschneider, was a pleasure to contribute!

**Pull request closed without merging**
