### PR TITLE
Add support for Jersey3 which is based on Jakarta EE 9 (#2748)

### LINKED ISSUE #2748: Support for Jersey 3 server
Jersey 3 has moved to using Jakarta EE 9. Basically most things under javax.* moved to jakarta.*.
Any plans to support this in micrometer? Maybe micrometer-jersey3?

### PR DESCRIPTION
**Pull request by alexsatori**
Basically copy pasted files from jersey2, changed javax.ws.rs.* to jakarta.ws.rs*
And some voodoo for the dependencies as jersey2 and jersey3 have different incompatible deps. 

Resolves #2748

### CODE REVIEW

**Review by shakuzen — COMMENTED** [review]
Thank you for the pull request. I suspect this approach of a micrometer-jersey3 module is probably the best route to go. It unfortunately means we have to make sure bugs common to both jersey modules get fixed in both. I'm wondering if it will make sense to drop the jersey2 module for Micrometer 2.0.
@mweirauch would you mind reviewing this if you have time?

**Comment by mweirauch** [comment]
@shakuzen I am currently on vacation and I am not sure I will be able to do a thorough review afterwards right away. I don't have any - neither testing nor production - projects which are using the Jersey3 framework.

**Comment by shakuzen** [comment]
Thanks for the quick response anyways @mweirauch and no worries.

**Comment by stefanbirkner** [comment]
> I'm wondering if it will make sense to drop the jersey2 module for Micrometer 2.0.
Micrometer should continue to support Jersey 2. Upgrading from Jersey 2 to 3 is not a simple step because javax.* classes are replaced by jakarta.* classes. Unfortunately some libraries like Guice don't work with jakarta.* classes which makes it harder to upgrade applications from Jersey 2 to Jersey 3.

**Comment by shakuzen** [comment]
Superseded by #2766

**Comment by shakuzen** [comment]
> Micrometer should continue to support Jersey 2.

My comment was in the context of moving the jersey instrumentation to micrometer-core that supports both Jersey 2 and Jersey 3. Not publishing the micrometer-jersey2 module would be because it becomes redundant with micrometer-core; not because we stop supporting Jersey 2.

**Pull request closed without merging**
