### PR TITLE
Add constants for base units

### PR DESCRIPTION
**Pull request by izeye**
This PR adds constants for base units as it would be nice to have sort of dictionary for base units for consistency and easy lookup.

### CODE REVIEW

**Comment by izeye** [comment]
@mweirauch @Simulant87 @shakuzen Thanks for the feedback!

If this is eligible for merging, I'll rebase this onto the current `1.0.x` branch.

@jkschneider Please let me know.

**Comment by OleksiiBondar** [comment]
Basic search against `micrometer-core` module gave me more files than changed here.
Here is an example for `"bytes"` 
image

Please check other units as well

**Comment by izeye** [comment]
@OleksiiBondar Thanks for the feedback! I guess you checked on the current `master` branch. This PR targeted for the `1.0.x` branch. I'll prepare for the `1.1.x` branch if this gets merged.

**Comment by shakuzen** [comment]
Sorry for the delay on this @izeye. I'll get this merged and check for any new places to use the constant in `1.0.x`

**Pull request merged**
