### PR TITLE
TimedAspect `timedClass` missing `shouldSkip` predicate check

### PR DESCRIPTION
**Pull request by aliaksei-astashenka**
Related to https://github.com/micrometer-metrics/micrometer/issues/3190, the part with missing shouldSkip check

### CODE REVIEW

**Review by shakuzen — APPROVED** [review]
Thank you.

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by jonatan-ivanov** [comment]
Shouldn't we fix this in `1.8.x`?

**Comment by jonatan-ivanov** [comment]
Fyi: I edited the original description of this PR so it will not close #3190 once it is merged, I think #3195 is the one that should close it.

**Comment by shakuzen** [comment]
> Shouldn't we fix this in `1.8.x`?

Yes, my plan was to rebase it on that. I just didn't get to it yesterday.

**Comment by shakuzen** [comment]
`timedClass` was only added in 1.9. I'll rebase onto `1.9.x`

**Pull request merged**
